---
- name: PLAY
  hosts: localhost
  connection: local
#  become_user: ubuntu
#  become: yes
  vars:
    # LIBRARY VERSIONS
    protoc_ver: 3.11.2
    proto_gen_go_version: 1.3.2
    helm_version: 3.3.4
    mockgen_version: 1.4.4
    controller_gen_version: 0.2.5
    kubectl_ver: v1.18.8
    kubebuilder_ver: 2.2.0
    user: {{ ansible_user_id }}

  roles:
    - role: setup
#    - role: andrewrothstein.protoc # check on mac, needs a 'protoc_platform: osx' variable
    - role: fubarhouse.golang
      become: yes
      vars:
        go_version: 1.14.2
        GO111MODULE: "on"
        GOPATH: /home/{{ fubarhouse_user }}/go
        fubarhouse_user:  user
        go_install_clean: true
        golang_shell_profile: /home/{{ fubarhouse_user }}/.bashrc # shell prof must be absolute path
        mode_codebase: 0755
        mode_workspace: 0755
        # go libraries
        go_get:
          - name: controller-gen
            url: "sigs.k8s.io/controller-tools/cmd/controller-gen@v{{ controller_gen_version }}"
            modules: true
          - name: mock-gen
            url: "github.com/golang/mock/mockgen@v{{ mockgen_version }}"
            modules: true
          - name: kind
            url: sigs.k8s.io/kind
            modules: true
          - name: protoc-gen-go
            url: "github.com/golang/protobuf/protoc-gen-go@v{{ proto_gen_go_version }}"
            modules: true
    - role: andrewrothstein.kubectl
    - role: andrewrothstein.kubebuilder
    - role: diodonfrost.terraform # check if this works on mac
      become: yes
    - role: andrewrothstein.k9s # TODO need to set k9s_os accordingly
#    - andrewrothstein.openjdk
#    - andrewrothstein.kops

# https://github.com/vaulttec/ansible-role-zsh
#  PATH=$PATH:/usr/local/kubebuilder/bin:/usr/local/go/bin:/usr/local/protoc/bin:/root/go/bin

