---

- name:

- name: Include OS-specific tasks (MAC OS)
  include_tasks: os-darwin.yml
  when: ansible_os_family == "Darwin"

- name: Include OS-specific tasks (Debian)
  include_tasks: os-debian.yml
  when: ansible_os_family == "Debian"
