---

# package module is supposedly platform agnostic
- name: Install common utils
  package:
    name:
      - curl
      - unzip
      - git
      - tar
      - wget
      - gcc
      - pkg-config
      - docker
      - zsh
      - zsh-syntax-highlighting
    state: present

- name: Include OS-specific tasks (MAC OS)
  include_tasks: os-darwin.yml
  when: ansible_os_family == "Darwin"

- name: Include OS-specific tasks (Debian)
  include_tasks: os-debian.yml
  when: ansible_os_family == "Debian"

- name: Protoc - download
  get_url:
    url: "https://github.com/protocolbuffers/protobuf/releases/download/v{{ protoc_ver }}/{{ protoc_endpoint }}"
    dest: "/tmp/{{ protoc_endpoint }}"
    validate_certs: no

- name: Protoc - check unpack directory
  file:
    path: /tmp/protoc
    state: directory

- name: Protoc - unpack
  unarchive:
    src: "/tmp/{{ protoc_endpoint }}"
    dest: /tmp/protoc
    mode: 0755

- name: Protoc - copy binary to /usr/local/bin
  become: yes
  copy:
    src: /tmp/protoc/bin/protoc
    dest: /usr/local/bin/protoc
    mode: 0755

