---

- name: "Configure protoc endpoint for Debian"
  set_fact:
    protoc_endpoint: "protoc-{{ protoc_version }}-linux-x86_64.zip"

- name: "apt | Install dependencies"
  apt:
    pkg: [ 'curl', 'gcc', 'git', 'findutils', 'make', 'rsync', 'tar', 'wget', 'unzip' ]
    state: present
  register: apt_result
  until: apt_result is success
  retries: 1
  delay: 2
  become: yes

- name: "Go-Lang | Define GOARCH"
  set_fact:
    GOARCH: "amd64"
  when: GOARCH is not defined

- name: "Go-Lang | Define GOOS"
  set_fact:
    GOOS: "linux"
  when: GOOS is not defined
